export const featuredBlogs = [
    {
      id: 1,
      title: "UPES Dehradun",
      description: "UPES Dehradun is known for its excellence in engineering, law, management, and applied sciences, offering industry-focused education and top-tier placements.",
      image: "/college1.jpg",
      link: "/blog/top-10-colleges-dehradun",
    },
    {
      id: 2,
      title: "Graphic Era Dehradun",
      description: "Graphic Era Deemed to be University is a leading institution in Dehradun, offering a wide range of courses in engineering, management, computer applications, and more.",
      image: "/college2.jpg",
      link: "/blog/why-study-in-dehradun",
    },
    {
      id: 3,
      title: "Dev Bhoomi Group of Institutions",
      description: "Dev Bhoomi Group of Institutions is a renowned college in Dehradun, offering courses in engineering, management, pharmacy, and more, with a focus on holistic development.",
      image: "/college3.jpg",
      link: "/blog/best-engineering-colleges",
    },
    {
      id: 4,
      title: "DIT University",
      description: "DIT University offers a variety of undergraduate and postgraduate programs in engineering, architecture, pharmacy, and management, with a strong emphasis on research and innovation.",
      image: "/college4.jpg",
      link: "/blog/dit-university",
    },
    {
      id: 5,
      title: "Shri Guru Ram Rai University",
      description: "Shri Guru Ram Rai University provides a wide range of courses in arts, science, commerce, and professional studies, focusing on quality education and holistic development.",
      image: "/college5.jpg",
      link: "/blog/sgrr-university",
    },
    {
      id: 6,
      title: "Himgiri Zee University",
      description: "Himgiri Zee University offers programs in agriculture, forestry, engineering, and media, aiming to provide practical knowledge and industry exposure to its students.",
      image: "/college6.png",
      link: "/blog/himgiri-zee-university",
    },
    {
      id: 7,
      title: "Uttarakhand Technical University",
      description: "Uttarakhand Technical University is a state university offering technical education in various fields, including engineering, management, and pharmacy, with a focus on research and development.",
      image: "/college7.jpg",
      link: "/blog/uttarakhand-technical-university",
    },
    {
      id: 8,
      title: "Doon University",
      description: "Doon University offers a range of undergraduate and postgraduate programs in arts, science, social science, and management, with a focus on interdisciplinary studies and research.",
      image: "/college8.jpg",
      link: "/blog/doon-university",
    },
    {
      id: 9,
      title: "IMS Unison University",
      description: "IMS Unison University provides quality education in law, management, mass communication, and liberal arts, with a strong emphasis on practical learning and industry exposure.",
      image: "/college9.jpg",
      link: "/blog/ims-unison-university",
    },
    {
      id: 10,
      title: "Swami Rama Himalayan University",
      description: "Swami Rama Himalayan University offers courses in medical sciences, nursing, engineering, and management, with a focus on holistic education and healthcare.",
      image: "/college10.jpg",
      link: "/blog/swami-rama-himalayan-university",
    },
    {
      id: 11,
      title: "Tula's Institute",
      description: "Tula's Institute is known for its excellence in engineering, management, and applied sciences, offering industry-focused education and top-tier placements.",
      image: "/college11.jpg",
      link: "/blog/tulas-institute",
    },
    {
      id: 12,
      title: "BFIT Group of Institutions",
      description: "BFIT Group of Institutions offers a variety of undergraduate and postgraduate programs in engineering, management, pharmacy, and more, with a strong emphasis on research and innovation.",
      image: "/college12.jpg",
      link: "/blog/bfit-group-of-institutions",
    },
    {
      id: 13,
      title: "Uttaranchal University",
      description: "Uttaranchal University provides a wide range of courses in arts, science, commerce, and professional studies, focusing on quality education and holistic development.",
      image: "/college13.png",
      link: "/blog/uttaranchal-university",
    },
    {
      id: 14,
      title: "Quantum University",
      description: "Quantum University offers programs in agriculture, forestry, engineering, and media, aiming to provide practical knowledge and industry exposure to its students.",
      image: "/college14.jpg",
      link: "/blog/quantum-university",
    },
    {
      id: 15,
      title: "Shivalik College of Engineering",
      description: "Shivalik College of Engineering is a state university offering technical education in various fields, including engineering, management, and pharmacy, with a focus on research and development.",
      image: "/college15.jpg",
      link: "/blog/shivalik-college-of-engineering",
    },
    {
      id: 16,
      title: "Beehive College of Engineering and Technology",
      description: "Beehive College of Engineering and Technology offers a range of undergraduate and postgraduate programs in arts, science, social science, and management, with a focus on interdisciplinary studies and research.",
      image: "/college16.jpg",
      link: "/blog/beehive-college-of-engineering-and-technology",
    },
];